version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/mardio/Projetos/financeiro:/app
    ports:
      - "8000:8000"
