# Generated by Django 5.0 on 2023-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_movimentacao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tbl_data', models.DateField(verbose_name='Data')),
                ('tbl_tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=100, verbose_name='Tipo')),
                ('tbl_valor', models.FloatField(verbose_name='Valor')),
                ('tbl_data_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tbl_obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
    ]
